# Generated by Django 5.0.7 on 2025-06-16 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapi', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prof_img', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('college', models.CharField(max_length=300, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('state', models.CharField(max_length=400, null=True)),
                ('Country', models.CharField(max_length=400, null=True)),
                ('city', models.CharField(max_length=500, null=True)),
                ('pin_code', models.IntegerField(null=True)),
                ('phone', models.IntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prof_img', models.ImageField(blank=True, null=True, upload_to='teacher/')),
                ('qualification', models.CharField(max_length=500, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
